export const data = [
  {
    id: 1,
    name: "Ring Device",
    icon: "/ring-icon.svg",
    type: "camera",
    slug: "ring-device",
  },
  {
    id: 2,
    name: "Ring Device",
    icon: "/ring-icon.svg",
    type: "camera",
    slug: "ring-device",
  },
  {
    id: 3,
    name: "Ring Device",
    icon: "/ring-icon.svg",
    type: "camera",
    slug: "ring-device",
  },
  {
    id: 4,
    name: "Yale Device",
    icon: "/yale-icon.svg",
    type: "locks",
    slug: "yale-device",
  },
  {
    id: 5,
    name: "Yale Device",
    icon: "/yale-icon.svg",
    type: "locks",
    slug: "yale-device",
  },
  {
    id: 6,
    name: "Nest Device",
    icon: "/google-icon.svg",
    type: "thermostats",
    slug: "nest-device",
  },
  {
    id: 7,
    name: "Philips Device",
    icon: "/philips-icon.svg",
    type: "lights",
    slug: "philips-device",
  },
];
