import type { Metadata } from "next";

import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Secure | سكيور",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const session = await getServerSession();
   
  return (
    <html lang="en">
      <body>
        <main>
          <div className=" bg-primary min-h-screen mx-auto flex flex-col text-white">
            <Navbar session={session} />
            <div className="lg:mx-14 mt-[130px]"> {children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
